// ============================================================
// SEED SCRIPT — My Bakery
// Run: node seed.js           (insert)
// Run: node seed.js --destroy (wipe + re-insert)
// ============================================================
require('dotenv').config();
const mongoose = require('mongoose');
const Category = require('./models/Category');
const Product  = require('./models/Product');

const MONGO_URI = process.env.MONGO_URI;
if (!MONGO_URI) {
  console.error('❌  MONGO_URI not found in .env');
  process.exit(1);
}

// ── Categories ────────────────────────────────────────────
const categoryData = [
  {
    name: 'Cakes',
    slug: 'cakes',
    description: 'Celebration cakes, layer cakes and custom designer cakes baked fresh to order.',
    image: { public_id: 'seed/cat-cakes', url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&q=80' },
    sortOrder: 1,
  },
  {
    name: 'Cupcakes',
    slug: 'cupcakes',
    description: 'Individual frosted cupcakes in a dozen flavours — perfect for parties and gifting.',
    image: { public_id: 'seed/cat-cupcakes', url: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=600&q=80' },
    sortOrder: 2,
  },
  {
    name: 'Cookies',
    slug: 'cookies',
    description: 'Crispy, chewy, and melt-in-your-mouth cookies baked fresh every day.',
    image: { public_id: 'seed/cat-cookies', url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600&q=80' },
    sortOrder: 3,
  },
  {
    name: 'Breads',
    slug: 'breads',
    description: 'Artisan sourdoughs, whole-wheat loaves, baguettes and more.',
    image: { public_id: 'seed/cat-breads', url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600&q=80' },
    sortOrder: 4,
  },
  {
    name: 'Pastries',
    slug: 'pastries',
    description: 'Buttery croissants, Danish pastries, eclairs and French delights.',
    image: { public_id: 'seed/cat-pastries', url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80' },
    sortOrder: 5,
  },
  {
    name: 'Brownies & Bars',
    slug: 'brownies-bars',
    description: 'Fudgy brownies, blondies and indulgent dessert bars.',
    image: { public_id: 'seed/cat-brownies', url: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=600&q=80' },
    sortOrder: 6,
  },
];

// ── Products (inserted after categories) ─────────────────
const buildProducts = (cats) => {
  const bySlug = {};
  cats.forEach((c) => { bySlug[c.slug] = c._id; });

  return [
    // ── CAKES ──────────────────────────────────────────────
    {
      name: 'Classic Chocolate Fudge Cake',
      slug: 'classic-chocolate-fudge-cake',
      description: 'A rich, moist three-layer chocolate cake filled with silky chocolate ganache and frosted with whipped dark chocolate buttercream. Made with premium Belgian cocoa for an intense, indulgent flavour.',
      shortDesc: 'Three-layer dark chocolate cake with ganache filling and buttercream frosting.',
      price: 1299,
      discountPrice: 1099,
      images: [
        { public_id: 'seed/p-choc-cake-1', url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=800&q=80' },
        { public_id: 'seed/p-choc-cake-2', url: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=800&q=80' },
      ],
      category: bySlug['cakes'],
      tags: ['chocolate', 'bestseller', 'celebration', 'layered'],
      ingredients: ['All-purpose flour', 'Belgian cocoa', 'Eggs', 'Butter', 'Caster sugar', 'Dark chocolate', 'Heavy cream'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '1 kg',
      servings: 12,
      preparationTime: '1-2 days',
      shelf: '3 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 20,
      customizable: true,
      flavors: ['Classic Chocolate', 'Dark Chocolate', 'Milk Chocolate'],
      sizes: [
        { name: '500g (6 servings)',  price: 749 },
        { name: '1 kg (12 servings)', price: 1299 },
        { name: '2 kg (24 servings)', price: 2399 },
      ],
    },
    {
      name: 'Strawberry Chiffon Cake',
      slug: 'strawberry-chiffon-cake',
      description: 'A light and airy chiffon cake layered with fresh whipped cream and sliced strawberries. Naturally coloured with real strawberry purée for a beautiful pink hue.',
      shortDesc: 'Light chiffon cake with fresh strawberries and whipped cream.',
      price: 1199,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-strawberry-cake-1', url: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=800&q=80' },
      ],
      category: bySlug['cakes'],
      tags: ['strawberry', 'light', 'fresh', 'seasonal'],
      ingredients: ['Cake flour', 'Eggs', 'Sugar', 'Vegetable oil', 'Strawberry purée', 'Heavy cream', 'Fresh strawberries'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '1 kg',
      servings: 10,
      preparationTime: '1-2 days',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 15,
      customizable: true,
      flavors: ['Strawberry', 'Mixed Berry', 'Mango'],
      sizes: [
        { name: '500g', price: 699 },
        { name: '1 kg', price: 1199 },
      ],
    },
    {
      name: 'Red Velvet Dream Cake',
      slug: 'red-velvet-dream-cake',
      description: 'The iconic deep-red velvet sponge paired with tangy cream cheese frosting. A bakery classic that never goes out of style — perfect for birthdays and anniversaries.',
      shortDesc: 'Classic red velvet sponge with cream cheese frosting.',
      price: 1349,
      discountPrice: 1149,
      images: [
        { public_id: 'seed/p-redvelvet-1', url: 'https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?w=800&q=80' },
      ],
      category: bySlug['cakes'],
      tags: ['red velvet', 'cream cheese', 'celebration', 'classic'],
      ingredients: ['All-purpose flour', 'Cocoa powder', 'Red food colour', 'Buttermilk', 'Eggs', 'Cream cheese', 'Icing sugar'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '1 kg',
      servings: 12,
      preparationTime: '1-2 days',
      shelf: '3 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 18,
      customizable: true,
      flavors: ['Classic Red Velvet'],
      sizes: [
        { name: '500g', price: 799 },
        { name: '1 kg', price: 1349 },
        { name: '2 kg', price: 2499 },
      ],
    },
    {
      name: 'Lemon Drizzle Cake',
      slug: 'lemon-drizzle-cake',
      description: 'A moist lemon sponge soaked in tangy lemon syrup and topped with a crisp lemon glaze. Fresh, zesty, and utterly irresistible.',
      shortDesc: 'Moist lemon sponge with tangy lemon drizzle glaze.',
      price: 899,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-lemon-cake-1', url: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?w=800&q=80' },
      ],
      category: bySlug['cakes'],
      tags: ['lemon', 'zesty', 'loaf', 'afternoon tea'],
      ingredients: ['Self-raising flour', 'Butter', 'Caster sugar', 'Eggs', 'Lemon zest', 'Lemon juice', 'Icing sugar'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '700g',
      servings: 8,
      preparationTime: '1 day',
      shelf: '4 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 25,
      customizable: false,
    },

    // ── CUPCAKES ────────────────────────────────────────────
    {
      name: 'Vanilla Swirl Cupcakes',
      slug: 'vanilla-swirl-cupcakes',
      description: 'Perfectly domed vanilla sponge cupcakes topped with a tall swirl of Madagascar vanilla bean buttercream. Decorated with edible sprinkles — a crowd favourite for any occasion.',
      shortDesc: 'Vanilla sponge topped with vanilla bean buttercream swirl.',
      price: 549,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-vanilla-cupcakes-1', url: 'https://images.unsplash.com/photo-1486427944299-d1955d23e34d?w=800&q=80' },
      ],
      category: bySlug['cupcakes'],
      tags: ['vanilla', 'classic', 'party', 'kids'],
      ingredients: ['Cake flour', 'Butter', 'Sugar', 'Eggs', 'Vanilla bean', 'Milk', 'Icing sugar'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '360g (6 pcs)',
      servings: 6,
      preparationTime: '1 day',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 40,
      minOrderQty: 6,
      maxOrderQty: 60,
      customizable: true,
      flavors: ['Vanilla', 'Chocolate', 'Strawberry', 'Lemon', 'Red Velvet'],
    },
    {
      name: 'Salted Caramel Cupcakes',
      slug: 'salted-caramel-cupcakes',
      description: 'Fluffy brown sugar cupcakes filled with a gooey salted caramel centre and crowned with caramel buttercream. Finished with a drizzle of sea-salt caramel sauce.',
      shortDesc: 'Brown sugar cupcakes with salted caramel filling and buttercream.',
      price: 649,
      discountPrice: 549,
      images: [
        { public_id: 'seed/p-salted-caramel-cupcakes-1', url: 'https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?w=800&q=80' },
      ],
      category: bySlug['cupcakes'],
      tags: ['caramel', 'salted caramel', 'indulgent', 'bestseller'],
      ingredients: ['Cake flour', 'Brown sugar', 'Butter', 'Eggs', 'Caramel sauce', 'Sea salt', 'Heavy cream'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '360g (6 pcs)',
      servings: 6,
      preparationTime: '1 day',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 35,
      minOrderQty: 6,
      maxOrderQty: 60,
      customizable: false,
    },

    // ── COOKIES ────────────────────────────────────────────
    {
      name: 'Double Chocolate Chip Cookies',
      slug: 'double-chocolate-chip-cookies',
      description: 'Thick, chewy cookies loaded with dark and milk chocolate chips. Made with brown butter for a rich, nutty depth of flavour. Perfectly crisp edges, gooey centre.',
      shortDesc: 'Chewy brown-butter cookies packed with dark & milk chocolate chips.',
      price: 399,
      discountPrice: 349,
      images: [
        { public_id: 'seed/p-choc-cookies-1', url: 'https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=800&q=80' },
      ],
      category: bySlug['cookies'],
      tags: ['chocolate chip', 'chewy', 'bestseller', 'everyday'],
      ingredients: ['All-purpose flour', 'Brown butter', 'Brown sugar', 'Eggs', 'Dark chocolate chips', 'Milk chocolate chips', 'Baking soda', 'Sea salt'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '250g (8 pcs)',
      servings: 8,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 50,
      minOrderQty: 4,
      maxOrderQty: 100,
      customizable: false,
    },
    {
      name: 'Classic Butter Cookies',
      slug: 'classic-butter-cookies',
      description: 'Delicate, melt-in-your-mouth Danish-style butter cookies made with 100% pure butter. Lightly sweetened and beautifully piped into rosette shapes — ideal for gifting.',
      shortDesc: 'Delicate melt-in-your-mouth Danish-style butter cookies.',
      price: 349,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-butter-cookies-1', url: 'https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=800&q=80' },
      ],
      category: bySlug['cookies'],
      tags: ['butter', 'danish', 'gift', 'classic'],
      ingredients: ['All-purpose flour', 'Unsalted butter', 'Icing sugar', 'Egg yolk', 'Vanilla extract'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '200g (12 pcs)',
      servings: 12,
      preparationTime: 'Same day',
      shelf: '7 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 60,
      minOrderQty: 6,
      maxOrderQty: 120,
      customizable: false,
    },
    {
      name: 'Oatmeal Raisin Cookies',
      slug: 'oatmeal-raisin-cookies',
      description: 'Wholesome, hearty cookies made with rolled oats, plump raisins, cinnamon and a touch of nutmeg. Soft in the centre, slightly crisp on the edges — a timeless classic.',
      shortDesc: 'Wholesome oat cookies with raisins and warm spices.',
      price: 329,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-oatmeal-cookies-1', url: 'https://images.unsplash.com/photo-1481391319762-47dff72954d9?w=800&q=80' },
      ],
      category: bySlug['cookies'],
      tags: ['oatmeal', 'raisin', 'wholesome', 'everyday'],
      ingredients: ['Rolled oats', 'All-purpose flour', 'Butter', 'Brown sugar', 'Eggs', 'Raisins', 'Cinnamon', 'Nutmeg'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '250g (8 pcs)',
      servings: 8,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: false,
      isBestseller: false,
      isAvailable: true,
      stock: 45,
      minOrderQty: 4,
      maxOrderQty: 100,
      customizable: false,
    },

    // ── BREADS ────────────────────────────────────────────
    {
      name: 'Classic Sourdough Loaf',
      slug: 'classic-sourdough-loaf',
      description: 'A naturally leavened sourdough loaf with a crackling, golden crust and an open, chewy crumb. Cold-fermented for 18 hours for superior flavour and digestibility.',
      shortDesc: 'Naturally leavened sourdough with 18-hour cold ferment.',
      price: 299,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-sourdough-1', url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=800&q=80' },
      ],
      category: bySlug['breads'],
      tags: ['sourdough', 'artisan', 'fermented', 'crusty'],
      ingredients: ['Bread flour', 'Water', 'Sourdough starter', 'Sea salt'],
      allergens: ['Gluten'],
      weight: '800g',
      servings: 10,
      preparationTime: '2 days',
      shelf: '4 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 20,
      customizable: false,
    },
    {
      name: 'Whole Wheat Multigrain Loaf',
      slug: 'whole-wheat-multigrain-loaf',
      description: 'A hearty, nutritious loaf packed with whole wheat flour, sunflower seeds, flax seeds, rolled oats, and sesame. Dense, flavourful, and perfect for everyday sandwiches.',
      shortDesc: 'Nutritious whole wheat loaf with seeds and rolled oats.',
      price: 249,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-multigrain-1', url: 'https://images.unsplash.com/photo-1549931319-a545dcf3bc7c?w=800&q=80' },
      ],
      category: bySlug['breads'],
      tags: ['whole wheat', 'multigrain', 'healthy', 'seeds'],
      ingredients: ['Whole wheat flour', 'Bread flour', 'Rolled oats', 'Sunflower seeds', 'Flax seeds', 'Sesame seeds', 'Yeast', 'Salt', 'Honey'],
      allergens: ['Gluten', 'Sesame'],
      weight: '700g',
      servings: 10,
      preparationTime: '1 day',
      shelf: '4 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 25,
      customizable: false,
    },
    {
      name: 'Garlic & Herb Focaccia',
      slug: 'garlic-herb-focaccia',
      description: 'A pillowy-soft Italian focaccia drizzled with extra-virgin olive oil, topped with roasted garlic, rosemary, sea salt flakes, and sun-dried tomatoes.',
      shortDesc: 'Pillowy focaccia with roasted garlic, rosemary and sea salt.',
      price: 279,
      discountPrice: 249,
      images: [
        { public_id: 'seed/p-focaccia-1', url: 'https://images.unsplash.com/photo-1586444248902-2f64eddc13df?w=800&q=80' },
      ],
      category: bySlug['breads'],
      tags: ['focaccia', 'garlic', 'italian', 'olive oil', 'herbs'],
      ingredients: ['Bread flour', 'Water', 'Yeast', 'Extra-virgin olive oil', 'Roasted garlic', 'Rosemary', 'Sea salt', 'Sun-dried tomatoes'],
      allergens: ['Gluten'],
      weight: '500g',
      servings: 6,
      preparationTime: '1 day',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 20,
      customizable: false,
    },

    // ── PASTRIES ───────────────────────────────────────────
    {
      name: 'Butter Croissants',
      slug: 'butter-croissants',
      description: 'Authentic French croissants made with 84% European butter and laminated dough folded 27 layers. Shatteringly crisp on the outside, airy and buttery within — baked fresh every morning.',
      shortDesc: 'Classic 27-layer French butter croissants, baked fresh daily.',
      price: 449,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-croissants-1', url: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=800&q=80' },
      ],
      category: bySlug['pastries'],
      tags: ['croissant', 'french', 'breakfast', 'buttery', 'flaky'],
      ingredients: ['French bread flour', 'European butter (84%)', 'Milk', 'Yeast', 'Sugar', 'Salt'],
      allergens: ['Gluten', 'Dairy'],
      weight: '240g (4 pcs)',
      servings: 4,
      preparationTime: '1 day',
      shelf: '1 day',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 30,
      minOrderQty: 2,
      customizable: false,
    },
    {
      name: 'Almond Danish Pastry',
      slug: 'almond-danish-pastry',
      description: 'Flaky laminated pastry filled with rich almond frangipane cream, baked to a deep golden colour and glazed with apricot jam. Topped with toasted flaked almonds.',
      shortDesc: 'Flaky danish with almond frangipane and toasted almonds.',
      price: 199,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-danish-1', url: 'https://images.unsplash.com/photo-1530610476181-d83430b64dcd?w=800&q=80' },
      ],
      category: bySlug['pastries'],
      tags: ['danish', 'almond', 'frangipane', 'flaky', 'breakfast'],
      ingredients: ['Pastry flour', 'Butter', 'Ground almonds', 'Sugar', 'Eggs', 'Apricot jam', 'Flaked almonds'],
      allergens: ['Gluten', 'Dairy', 'Eggs', 'Tree nuts'],
      weight: '120g (1 pc)',
      servings: 1,
      preparationTime: '1 day',
      shelf: '1 day',
      isFeatured: false,
      isBestseller: true,
      isAvailable: true,
      stock: 40,
      minOrderQty: 2,
      customizable: false,
    },
    {
      name: 'Chocolate Éclair',
      slug: 'chocolate-eclair',
      description: 'Classic French éclairs made with light choux pastry, filled with silky vanilla pastry cream and topped with a glossy dark chocolate glaze.',
      shortDesc: 'Choux pastry filled with vanilla cream, topped with chocolate glaze.',
      price: 229,
      discountPrice: 199,
      images: [
        { public_id: 'seed/p-eclair-1', url: 'https://images.unsplash.com/photo-1603532648955-039310d9ed75?w=800&q=80' },
      ],
      category: bySlug['pastries'],
      tags: ['éclair', 'choux', 'french', 'cream', 'chocolate'],
      ingredients: ['Plain flour', 'Butter', 'Eggs', 'Water', 'Vanilla bean', 'Milk', 'Cornstarch', 'Dark chocolate'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '100g (1 pc)',
      servings: 1,
      preparationTime: '1 day',
      shelf: '1 day',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 30,
      minOrderQty: 2,
      customizable: false,
    },

    // ── BROWNIES & BARS ────────────────────────────────────
    {
      name: 'Fudgy Dark Chocolate Brownies',
      slug: 'fudgy-dark-chocolate-brownies',
      description: 'Ultra-fudgy, crackle-top brownies made with 70% dark chocolate and Dutch-processed cocoa. Dense, rich and intensely chocolatey — the way brownies should be.',
      shortDesc: 'Dense, crackle-top brownies with 70% dark chocolate.',
      price: 499,
      discountPrice: 449,
      images: [
        { public_id: 'seed/p-brownies-1', url: 'https://images.unsplash.com/photo-1564355808539-22fda35bed7e?w=800&q=80' },
      ],
      category: bySlug['brownies-bars'],
      tags: ['brownie', 'fudgy', 'dark chocolate', 'bestseller'],
      ingredients: ['70% dark chocolate', 'Butter', 'Caster sugar', 'Eggs', 'Dutch-process cocoa', 'Plain flour', 'Sea salt'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '400g (9 pcs)',
      servings: 9,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 30,
      customizable: true,
      flavors: ['Plain Dark Chocolate', 'Walnut', 'Cream Cheese Swirl', 'Nutella Swirl'],
    },
    {
      name: 'Blueberry Oat Bars',
      slug: 'blueberry-oat-bars',
      description: 'Hearty oat-based bars with a buttery crumble top and bottom, sandwiching a layer of sweet, jammy blueberry filling. A wholesome snack or breakfast bar.',
      shortDesc: 'Buttery oat crumble bars with blueberry jam filling.',
      price: 399,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-oat-bars-1', url: 'https://images.unsplash.com/photo-1490567674331-8a1d4d4b0a3a?w=800&q=80' },
      ],
      category: bySlug['brownies-bars'],
      tags: ['oat', 'blueberry', 'wholesome', 'snack bar'],
      ingredients: ['Rolled oats', 'Plain flour', 'Butter', 'Brown sugar', 'Blueberry jam', 'Lemon zest', 'Baking powder'],
      allergens: ['Gluten', 'Dairy'],
      weight: '350g (8 pcs)',
      servings: 8,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 35,
      customizable: false,
    },
    {
      name: 'Salted Caramel Blondies',
      slug: 'salted-caramel-blondies',
      description: 'White-chocolate-base blondies swirled with generous ribbons of salted caramel sauce. Chewy, buttery and perfectly balanced between sweet and salty.',
      shortDesc: 'Chewy white chocolate blondies with salted caramel swirl.',
      price: 479,
      discountPrice: 429,
      images: [
        { public_id: 'seed/p-blondies-1', url: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=800&q=80' },
      ],
      category: bySlug['brownies-bars'],
      tags: ['blondie', 'caramel', 'white chocolate', 'chewy'],
      ingredients: ['White chocolate', 'Butter', 'Brown sugar', 'Eggs', 'Plain flour', 'Caramel sauce', 'Sea salt'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '400g (9 pcs)',
      servings: 9,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 25,
      customizable: false,
    },

    // ── ADDITIONAL CAKES ───────────────────────────────────
    {
      name: 'Black Forest Gateau',
      slug: 'black-forest-gateau',
      description: 'A classic German Black Forest cake made with moist chocolate sponge layers, soaked in Kirsch syrup, filled with fresh whipped cream and Morello cherries, topped with chocolate shavings.',
      shortDesc: 'Chocolate sponge with Kirsch, whipped cream and Morello cherries.',
      price: 1449,
      discountPrice: 1249,
      images: [
        { public_id: 'seed/p-blackforest-1', url: 'https://images.unsplash.com/photo-1611293388250-580b08c4a145?w=800&q=80' },
      ],
      category: bySlug['cakes'],
      tags: ['black forest', 'cherry', 'chocolate', 'classic', 'celebration'],
      ingredients: ['All-purpose flour', 'Cocoa powder', 'Eggs', 'Sugar', 'Butter', 'Morello cherries', 'Heavy cream', 'Kirsch syrup', 'Dark chocolate'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '1 kg',
      servings: 12,
      preparationTime: '1-2 days',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 15,
      customizable: true,
      sizes: [
        { name: '500g (6 servings)',  price: 849 },
        { name: '1 kg (12 servings)', price: 1449 },
        { name: '2 kg (24 servings)', price: 2699 },
      ],
    },
    {
      name: 'Mango Mousse Cake',
      slug: 'mango-mousse-cake',
      description: 'A light and refreshing no-bake mango mousse cake with a buttery digestive biscuit base, silky Alphonso mango mousse filling, and a vibrant mango mirror glaze on top.',
      shortDesc: 'Light Alphonso mango mousse with biscuit base and mirror glaze.',
      price: 1099,
      discountPrice: 949,
      images: [
        { public_id: 'seed/p-mango-mousse-1', url: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=800&q=80' },
      ],
      category: bySlug['cakes'],
      tags: ['mango', 'mousse', 'summer', 'no-bake', 'seasonal'],
      ingredients: ['Digestive biscuits', 'Butter', 'Alphonso mango purée', 'Heavy cream', 'Cream cheese', 'Gelatin', 'Sugar'],
      allergens: ['Gluten', 'Dairy'],
      weight: '800g',
      servings: 10,
      preparationTime: '1-2 days',
      shelf: '2 days',
      isFeatured: true,
      isNew: true,
      isAvailable: true,
      stock: 12,
      customizable: false,
    },

    // ── ADDITIONAL CUPCAKES ────────────────────────────────
    {
      name: 'Chocolate Truffle Cupcakes',
      slug: 'chocolate-truffle-cupcakes',
      description: 'Intensely rich chocolate sponge cupcakes with a hidden dark chocolate truffle centre, topped with silky chocolate ganache frosting and a dusting of cocoa powder.',
      shortDesc: 'Dark chocolate cupcakes with truffle centre and ganache frosting.',
      price: 699,
      discountPrice: 599,
      images: [
        { public_id: 'seed/p-choc-truffle-cupcakes-1', url: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?w=800&q=80' },
      ],
      category: bySlug['cupcakes'],
      tags: ['chocolate', 'truffle', 'ganache', 'indulgent', 'bestseller'],
      ingredients: ['Cake flour', 'Dutch-process cocoa', 'Butter', 'Sugar', 'Eggs', 'Dark chocolate', 'Heavy cream'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '420g (6 pcs)',
      servings: 6,
      preparationTime: '1 day',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: true,
      isAvailable: true,
      stock: 30,
      minOrderQty: 6,
      maxOrderQty: 60,
      customizable: true,
      flavors: ['Dark Chocolate', 'Milk Chocolate', 'White Chocolate'],
    },
    {
      name: 'Red Velvet Cupcakes',
      slug: 'red-velvet-cupcakes',
      description: 'Stunning red velvet cupcakes with a velvety, tender crumb and a tall swirl of tangy cream cheese frosting. Decorated with red velvet crumbs — a visual and flavour showstopper.',
      shortDesc: 'Red velvet cupcakes with tall cream cheese frosting swirl.',
      price: 649,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-redvelvet-cupcakes-1', url: 'https://images.unsplash.com/photo-1562440499-64916757fd81?w=800&q=80' },
      ],
      category: bySlug['cupcakes'],
      tags: ['red velvet', 'cream cheese', 'classic', 'celebration'],
      ingredients: ['Cake flour', 'Cocoa powder', 'Red food colour', 'Buttermilk', 'Eggs', 'Butter', 'Cream cheese', 'Icing sugar'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '360g (6 pcs)',
      servings: 6,
      preparationTime: '1 day',
      shelf: '2 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 35,
      minOrderQty: 6,
      maxOrderQty: 60,
      customizable: false,
    },

    // ── ADDITIONAL COOKIES ─────────────────────────────────
    {
      name: 'Snickerdoodle Cookies',
      slug: 'snickerdoodle-cookies',
      description: 'Soft, pillowy cookies rolled in a cinnamon-sugar mixture and baked to a perfect golden crinkle. Made with cream of tartar for the classic tangy snickerdoodle flavour.',
      shortDesc: 'Soft cinnamon-sugar rolled cookies with golden crinkle tops.',
      price: 349,
      discountPrice: 299,
      images: [
        { public_id: 'seed/p-snickerdoodle-1', url: 'https://images.unsplash.com/photo-1548365328-8c6db3220e4c?w=800&q=80' },
      ],
      category: bySlug['cookies'],
      tags: ['cinnamon', 'soft', 'classic', 'american', 'everyday'],
      ingredients: ['All-purpose flour', 'Butter', 'Caster sugar', 'Eggs', 'Cream of tartar', 'Baking soda', 'Cinnamon', 'Salt'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '250g (8 pcs)',
      servings: 8,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 50,
      minOrderQty: 4,
      maxOrderQty: 100,
      customizable: false,
    },
    {
      name: 'White Chocolate Macadamia Cookies',
      slug: 'white-chocolate-macadamia-cookies',
      description: 'Golden, chewy cookies loaded with creamy white chocolate chunks and whole toasted macadamia nuts. A premium, indulgent treat with a rich buttery base.',
      shortDesc: 'Chewy cookies with white chocolate chunks and toasted macadamia nuts.',
      price: 449,
      discountPrice: 399,
      images: [
        { public_id: 'seed/p-macadamia-cookies-1', url: 'https://images.unsplash.com/photo-1590080875897-f5476f5e1f47?w=800&q=80' },
      ],
      category: bySlug['cookies'],
      tags: ['white chocolate', 'macadamia', 'premium', 'chewy', 'nutty'],
      ingredients: ['All-purpose flour', 'Butter', 'Brown sugar', 'Caster sugar', 'Eggs', 'White chocolate chips', 'Macadamia nuts', 'Vanilla extract'],
      allergens: ['Gluten', 'Dairy', 'Eggs', 'Tree nuts'],
      weight: '280g (8 pcs)',
      servings: 8,
      preparationTime: 'Same day',
      shelf: '5 days',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 40,
      minOrderQty: 4,
      maxOrderQty: 100,
      customizable: false,
    },

    // ── ADDITIONAL BREADS ──────────────────────────────────
    {
      name: 'Cinnamon Raisin Swirl Bread',
      slug: 'cinnamon-raisin-swirl-bread',
      description: 'A soft, pillowy enriched white bread swirled with a generous cinnamon-brown sugar filling and plump golden raisins. Perfect toasted with a pat of butter.',
      shortDesc: 'Enriched white bread with cinnamon-sugar swirl and golden raisins.',
      price: 329,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-cinnamon-bread-1', url: 'https://images.unsplash.com/photo-1567881199698-d5c22a8b8c61?w=800&q=80' },
      ],
      category: bySlug['breads'],
      tags: ['cinnamon', 'raisin', 'sweet bread', 'breakfast', 'loaf'],
      ingredients: ['Bread flour', 'Milk', 'Butter', 'Eggs', 'Yeast', 'Sugar', 'Cinnamon', 'Brown sugar', 'Golden raisins'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '600g',
      servings: 8,
      preparationTime: '1 day',
      shelf: '4 days',
      isFeatured: false,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 20,
      customizable: false,
    },
    {
      name: 'Classic French Baguette',
      slug: 'classic-french-baguette',
      description: 'A traditional French baguette with a shatteringly crisp, golden crust and a light, airy open crumb. Made with only four ingredients — flour, water, yeast, and salt — and baked to perfection.',
      shortDesc: 'Traditional French baguette — crisp crust, airy open crumb.',
      price: 149,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-baguette-1', url: 'https://images.unsplash.com/photo-1545696968-1a31ea033800?w=800&q=80' },
      ],
      category: bySlug['breads'],
      tags: ['baguette', 'french', 'artisan', 'crusty', 'everyday'],
      ingredients: ['Bread flour', 'Water', 'Yeast', 'Salt'],
      allergens: ['Gluten'],
      weight: '250g (1 pc)',
      servings: 4,
      preparationTime: '1 day',
      shelf: '1 day',
      isFeatured: false,
      isBestseller: true,
      isAvailable: true,
      stock: 30,
      minOrderQty: 1,
      customizable: false,
    },

    // ── ADDITIONAL PASTRIES ────────────────────────────────
    {
      name: 'Classic Cinnamon Rolls',
      slug: 'classic-cinnamon-rolls',
      description: 'Pillowy-soft enriched dough rolls generously filled with cinnamon-brown sugar butter, baked until golden and finished with a thick vanilla cream cheese glaze. Warm, gooey and utterly irresistible.',
      shortDesc: 'Soft cinnamon rolls with brown sugar filling and cream cheese glaze.',
      price: 549,
      discountPrice: 499,
      images: [
        { public_id: 'seed/p-cinnamon-rolls-1', url: 'https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80' },
      ],
      category: bySlug['pastries'],
      tags: ['cinnamon roll', 'soft', 'gooey', 'breakfast', 'american'],
      ingredients: ['Bread flour', 'Milk', 'Butter', 'Eggs', 'Yeast', 'Sugar', 'Cinnamon', 'Brown sugar', 'Cream cheese', 'Icing sugar', 'Vanilla'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '480g (4 pcs)',
      servings: 4,
      preparationTime: '1 day',
      shelf: '2 days',
      isFeatured: true,
      isBestseller: true,
      isNew: true,
      isAvailable: true,
      stock: 25,
      minOrderQty: 2,
      customizable: true,
      flavors: ['Classic Cinnamon', 'Nutella', 'Apple Cinnamon'],
    },
    {
      name: 'Strawberry Tart',
      slug: 'strawberry-tart',
      description: 'A buttery pâte sablée tart shell filled with silky vanilla pastry cream and topped with a beautiful arrangement of fresh, glazed strawberries. Elegant, simple, and stunning.',
      shortDesc: 'Crisp pastry shell with vanilla cream and fresh glazed strawberries.',
      price: 649,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-strawberry-tart-1', url: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800&q=80' },
      ],
      category: bySlug['pastries'],
      tags: ['tart', 'strawberry', 'french', 'fresh fruit', 'elegant'],
      ingredients: ['Plain flour', 'Butter', 'Icing sugar', 'Egg yolk', 'Milk', 'Vanilla bean', 'Cornstarch', 'Fresh strawberries', 'Apricot glaze'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '350g (4 servings)',
      servings: 4,
      preparationTime: '1 day',
      shelf: '1 day',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 15,
      minOrderQty: 1,
      customizable: false,
    },

    // ── ADDITIONAL BROWNIES & BARS ─────────────────────────
    {
      name: 'Raspberry Cheesecake Bars',
      slug: 'raspberry-cheesecake-bars',
      description: 'A golden buttery shortbread base topped with a thick layer of tangy cream cheese filling swirled with vibrant raspberry coulis, then baked until just set. Creamy, fruity and utterly indulgent.',
      shortDesc: 'Shortbread base with cream cheese filling and raspberry swirl.',
      price: 529,
      discountPrice: 479,
      images: [
        { public_id: 'seed/p-raspberry-cheesecake-bars-1', url: 'https://images.unsplash.com/photo-1621303837174-89787a7d4729?w=800&q=80' },
      ],
      category: bySlug['brownies-bars'],
      tags: ['cheesecake', 'raspberry', 'fruity', 'cream cheese', 'premium'],
      ingredients: ['Plain flour', 'Butter', 'Icing sugar', 'Cream cheese', 'Sugar', 'Eggs', 'Vanilla', 'Fresh raspberries', 'Lemon juice'],
      allergens: ['Gluten', 'Dairy', 'Eggs'],
      weight: '400g (9 pcs)',
      servings: 9,
      preparationTime: 'Same day',
      shelf: '4 days',
      isFeatured: true,
      isBestseller: false,
      isNew: true,
      isAvailable: true,
      stock: 20,
      customizable: false,
    },
    {
      name: 'Rocky Road Bars',
      slug: 'rocky-road-bars',
      description: 'A no-bake chocolate bar loaded with mini marshmallows, crushed digestive biscuits, roasted peanuts and glacé cherries, all bound in a rich dark chocolate coating. A chocoholic\'s dream.',
      shortDesc: 'No-bake dark chocolate bars with marshmallows, nuts and biscuits.',
      price: 449,
      discountPrice: 0,
      images: [
        { public_id: 'seed/p-rocky-road-1', url: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&q=80' },
      ],
      category: bySlug['brownies-bars'],
      tags: ['rocky road', 'no-bake', 'chocolate', 'marshmallow', 'nuts', 'kids'],
      ingredients: ['Dark chocolate', 'Butter', 'Golden syrup', 'Mini marshmallows', 'Digestive biscuits', 'Roasted peanuts', 'Glacé cherries'],
      allergens: ['Gluten', 'Dairy', 'Peanuts'],
      weight: '350g (9 pcs)',
      servings: 9,
      preparationTime: 'Same day',
      shelf: '7 days',
      isFeatured: false,
      isBestseller: true,
      isAvailable: true,
      stock: 40,
      customizable: true,
      flavors: ['Classic', 'Peanut Butter', 'Mint Chocolate'],
    },
  ];
};

// ── Main ──────────────────────────────────────────────────
async function seed() {
  await mongoose.connect(MONGO_URI, { serverSelectionTimeoutMS: 8000, family: 4 });
  console.log('✅  MongoDB connected');

  const destroy = process.argv.includes('--destroy');

  if (destroy) {
    await Category.deleteMany({});
    await Product.deleteMany({});
    console.log('🗑   Cleared existing categories and products');
  }

  // Insert categories (skip existing slugs)
  const existingCatSlugs = (await Category.find({}, 'slug')).map((c) => c.slug);
  const newCats = categoryData.filter((c) => !existingCatSlugs.includes(c.slug));

  let insertedCats = [];
  if (newCats.length) {
    insertedCats = await Category.insertMany(newCats);
    console.log(`📂  Inserted ${insertedCats.length} new categories`);
  } else {
    console.log('📂  All categories already exist — skipping');
  }

  // Reload all categories for ID lookup
  const allCats = await Category.find({});
  const products = buildProducts(allCats);

  // Insert products (skip existing slugs)
  const existingProdSlugs = (await Product.find({}, 'slug')).map((p) => p.slug);
  const newProds = products.filter((p) => !existingProdSlugs.includes(p.slug));

  if (newProds.length) {
    await Product.insertMany(newProds);
    console.log(`🥐  Inserted ${newProds.length} new products`);
  } else {
    console.log('🥐  All products already exist — skipping');
  }

  console.log('\n✅  Seed complete!\n');
  console.log('Summary:');
  console.log(`   Categories : ${await Category.countDocuments()}`);
  console.log(`   Products   : ${await Product.countDocuments()}`);

  await mongoose.disconnect();
  process.exit(0);
}

seed().catch((err) => {
  console.error('❌  Seed failed:', err.message);
  process.exit(1);
});
